apiVersion: apps/v1
kind: Deployment
metadata:
  name: ld-deployment
  labels:
    app: ld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ld
  template:
    metadata:
      labels:
        app: ld
    spec:
      imagePullSecrets:
        - name: dockerregistrykey
      containers:
        - name: ld
          image: {{ .Values.registry }}:{{ .Values.tag }}
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8003
          env:
            - name: RM_HOST
              value: "rm-service:8005"
